language: php

os:
- linux

php:
- 7.0
- 7.1
- 7.2
- 7.3

matrix:
  fast_finish: true

before_script:
- flags="--prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress "
- composer install $flags -vv

script:
- mkdir .reports
# Code style
- php vendor/bin/phpcs ./src --standard=PSR1 --encoding=utf-8 --report=summary
- php vendor/bin/phpcs ./src --standard=PSR2 --encoding=utf-8 --report=summary
# PHPUnit tests
- php vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=.reports/clover.xml

after_success:
# Send cover
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover .reports/clover.xml

cache:
  directories:
  - $HOME/.composer/cache

addons:
  apt:
    packages:
    - parallel

git:
  depth: 1

notifications:
  email:
  - mail@igusev.ru
